export const USER_INFORMATION_UPDATE = "USER_INFORMATION_UPDATE";
export const SAVE_USER_INFORMATION = "SAVE_USER_INFORMATION";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const UPDATE_LOGIN_INFO = "UPDATE_LOGIN_INFO";
