export const USER_INFORMATION_UPDATE = "USER_INFORMATION_UPDATE";
export const SAVE_USER_INFORMATION = "SAVE_USER_INFORMATION";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const UPDATE_LOGIN_INFO = "UPDATE_LOGIN_INFO";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const GET_MATCHES = "GET_MATCHES";

export const FETCH_LATEST_USER = "FETCH_LATEST_USER";
export const FETCH_MATCHES = "FETCH_MATCHES";
